### ISSUE TITLE
! in password does not work

### ISSUE THREAD

**Issue by cmh716** [albertnis/mqcontrol#11]
Trying to connect to a broker with userid and password will not work if the password contains an exclamation point. 

-u chris -p "P5sdfs!DFGgdfgDFG"
bash: !DFGgdfgDFG": event not found

**Comment by albertnis** [comment]
Sounds like this could be caused by the shell attempting to interpolate your input. Could you try again using single quotes around the password? I think in bash that will make it interpret the string literally.

**Comment by cmh716** [comment]
Sorry about that,  I previously tried with double quotes and it did not work.  Your advice worked.  Thanks!  I am just starting out trying to use your tool and it seems quite useful.  It compiled on an M1 Mac fine.  Thanks again

**Comment by albertnis** [comment]
Great! I have actually been meaning to add a pre-built binary for Apple Silicon (#10). Sorry you had to build it yourself for now!

If you notice any other missing functionality or issues feel free to open another issue as a feature request or bug report.

**Comment by albertnis** [comment]
Just wanted to note that as of [v0.4.2](https://github.com/albertnis/mqcontrol/releases/tag/v0.4.2), there is an Apple Silicon build being automatically created with each release. Hope that is helpful and works for you!

**Comment by cmh716** [comment]
Thank you so much!
